import b from "@/public/b.png";
import c from "@/public/c.png";
import d from "@/public/d.png";
import music2 from "@/public/music2.jpg";
import quiz from "@/public/quiz.jpeg";
import earTraining from "@/public/earTraining.jpeg";

export const curriculumArray = [
    {
        id: 1,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessons: "16 Lessons",
        level: "Beginner",
        progress: 60,
    },
    {
        id: 2,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessons: "6 Lessons",
        level: "Amateur",
        progress: 10,
    },
    {
        id: 3,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessons: "16 Lessons",
        level: "Intermediate",
        progress: 0,
    },
    {
        id: 4,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
        progress: 100,
    },
    {
        id: 5,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessons: "16 Lessons",
        level: "Beginner",
        progress: 25,

    },
    {
        id: 6,
        image: c,
        title: "Get your Free Course Welcome to Spicy Guitar Academy",
        description: "Blizzlefrink zopplewump, snoodleflip drabblewock, glimberkramp snoozletrap. Frizzleplop wibbleklunk, snarglewhip flizzleframp, krindlefizz snoozleplunk. Plizzlewhorf snibbletrap, dribblefrump snoozlewhack, zindleflax glimberflip",
        lessons: "16 lLssons",
        level: "Amateur",
        progress: 60,
    },
    {
        id: 7,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 8,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
    {
        id: 9,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessons: "16 Lessons",
        level: "Beginner",
    },
    {
        id: 10,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessons: "6 Lessons",
        level: "Amateur",
    },
    {
        id: 11,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 12,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
    {
        id: 13,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessons: "16 Lessons",
        level: "Beginner",
    },
    {
        id: 14,
        image: c,
        title: "Get your Free Course Welcome to Spicy Guitar Academy",
        description: "Blizzlefrink zopplewump, snoodleflip drabblewock, glimberkramp snoozletrap. Frizzleplop wibbleklunk, snarglewhip flizzleframp, krindlefizz snoozleplunk. Plizzlewhorf snibbletrap, dribblefrump snoozlewhack, zindleflax glimberflip",
        lessons: "16 lLssons",
        level: "Amateur",
    },
    {
        id: 15,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 16,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
    {
        id: 17,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessons: "16 Lessons",
        level: "Beginner",
    },
    {
        id: 18,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessons: "6 Lessons",
        level: "Amateur",
    },
    {
        id: 19,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 20,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
    {
        id: 21,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessons: "16 Lessons",
        level: "Beginner",
    },
    {
        id: 22,
        image: c,
        title: "Get your Free Course Welcome to Spicy Guitar Academy",
        description: "Blizzlefrink zopplewump, snoodleflip drabblewock, glimberkramp snoozletrap. Frizzleplop wibbleklunk, snarglewhip flizzleframp, krindlefizz snoozleplunk. Plizzlewhorf snibbletrap, dribblefrump snoozlewhack, zindleflax glimberflip",
        lessons: "16 lLssons",
        level: "Amateur",
    },
    {
        id: 23,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 24,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
    {
        id: 25,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessons: "16 Lessons",
        level: "Beginner",
    },
    {
        id: 26,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessons: "6 Lessons",
        level: "Amateur",
    },
    {
        id: 27,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 28,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
    {
        id: 29,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessons: "16 Lessons",
        level: "Beginner",
    },
    {
        id: 30,
        image: c,
        title: "Get your Free Course Welcome to Spicy Guitar Academy",
        description: "Blizzlefrink zopplewump, snoodleflip drabblewock, glimberkramp snoozletrap. Frizzleplop wibbleklunk, snarglewhip flizzleframp, krindlefizz snoozleplunk. Plizzlewhorf snibbletrap, dribblefrump snoozlewhack, zindleflax glimberflip",
        lessons: "16 lLssons",
        level: "Amateur",
    },
    {
        id: 31,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessons: "16 Lessons",
        level: "Intermediate",
    },
    {
        id: 32,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessons: "5 Lessons",
        level: "Advance",
    },
]
