import b from "@/public/b.png";
import c from "@/public/c.png";
import d from "@/public/d.png";
import music2 from "@/public/music2.jpg";
import quiz from "@/public/quiz.jpeg";
import earTraining from "@/public/earTraining.jpeg";
import {curriculumArray} from "@/app/(student)/(home)/(pages)/curriculum/curriculumArrays";

export const courses = [
    {
        id: 1,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessonsCount: "6 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: [
            {
                id: 1,
                image: b,
                title: "Join our  whatsapp group",
                description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
                lessons: "16 Lessons",
                level: "Beginner",
                progress: 60,
            },
            {
                id: 2,
                image: c,
                title: "Get your Free Course",
                description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
                lessons: "6 Lessons",
                level: "Amateur",
                progress: 10,
            },
        ]
    },
    {
        id: 2,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessonsCount: "16 Lessons",
        level: "Amateur",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: [
            {
                id: 1,
                image: d,
                title: "App Tour",
                description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
                lessons: "16 Lessons",
                level: "Intermediate",
                progress: 0,
            },
            {
                id: 2,
                image: music2,
                title: "Get your Free Course",
                description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
                lessons: "5 Lessons",
                level: "Advance",
                progress: 100,
            },
        ],
    },
    {
        id: 3,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 4,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 5,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 6,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 7,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 8,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 9,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessonsCount: "16 Lessons",
        level: "Amateur",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 10,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 11,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 12,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 13,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 14,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 15,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 16,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessonsCount: "16 Lessons",
        level: "Amateur",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 17,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 18,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 19,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 20,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 21,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 22,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 23,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessonsCount: "16 Lessons",
        level: "Amateur",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 24,
        image: d,
        title: "App Tour",
        description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 25,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "16 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 26,
        image: quiz,
        title: "Quiz",
        description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
        lessonsCount: "16 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 27,
        image: earTraining,
        title: "Ear Training",
        description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
        lessonsCount: "16 Lessons",
        level: "Intermediate",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
    {
        id: 28,
        image: music2,
        title: "Get your Free Course",
        description: "Flizzleworp drabblequack, snoozlefrink wibbleflap, kraznibble floobersnack. Twizzleflomp glibberplunk, snoorflekrip brizzlewop, zindlefrap snoodlewhack. Grozzleflip blizzlekrink, drumblepuff snoozlepop skizzlefrip",
        lessonsCount: "5 Lessons",
        level: "Advance",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: curriculumArray.slice(0, Math.ceil(curriculumArray.length/8)),
    },
]


export const coursess = [
    {
        id: 1,
        image: b,
        title: "Join our  whatsapp group",
        description: "Zarflin wamble snoozetrop, kinkleblot flarbin doozlewhip. Gribbleflox zindlewump, prazzlequack flibbityplop dranzoodle. Worblesnack zizzlefrap, glimberwoosh snoodlepop krimbleflop. Frizzlewump, glorbitysnack, dringlewobble snoof.",
        lessonsCount: "6 Lessons",
        level: "Beginner",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: [
            {
                id: 10,
                image: quiz,
                title: "Quiz",
                description: "Womblefrizz snoodlequack, grizzleplunk dribberflap, snorflequib zopplefrink. Frizzleklap blooberwump, skindlewharp dribblezorb, snoozletrap glimberplop. Zogglefritz plizzleflamp, zindlekrimp snooflewhip, frizzletrap snargleflip",
                lessons: "16 Lessons",
                level: "Beginner",
                progress: 10,
            },
            {
                id: 20,
                image: earTraining,
                title: "Ear Training",
                description: "Blorpfizzle whacklesnug, drabbleflonk snoofletrap, quizzleflop zindlewhack. Frabblenorp wizzleflick, glibblefroop zindlequack, snoodlefrimp dribblewomp. Wombleflip snarglequix, frizzlewhack blorplezorb, skizzleflap snozzlepuff.",
                lessons: "16 Lessons",
                level: "Intermediate",
                progress: 10,
            },
        ]
    },
    {
        id: 2,
        image: c,
        title: "Get your Free Course",
        description: "Blibberflunk drozzlewhip, skreebop wuzzlenorf, crindleplunk zopadoodle. Jibberflop snarglequix, plizzlewharf drabblewoop. Frizzlekrimp zundleflip, whizzlepop gloopersnack, bringlefroop snoozlekrink.",
        lessonsCount: "16 Lessons",
        level: "Amateur",
        unknownNumber: 3,
        duration: "01:08:55",
        lessons: [
            {
                id: 11,
                image: d,
                title: "App Tour",
                description: "Snizzlewump glimmerflap, dribblezink frozzleplunk, quibbletrap snoorblewoosh. Wizzlefrump krindlewhack, zopplegorp flibblemunch, glimberwhip snoozleflip",
                lessons: "16 Lessons",
                level: "Intermediate",
                progress: 0,
            },
        ],
    },
]